### PR TITLE
Upgrade ShortcutBadger to 1.1.17

### PR DESCRIPTION
**Pull request by excendia**
To solved the problem of badge on android 7

### CODE REVIEW

**Comment by an5rag** [comment]
What's the status of the PR? We're using the plugin in our project and urgently need this to go in.

**Comment by marianoarga** [comment]
@an5rag if you really need this change you can grab the code from the @katzer fork

**Comment by SudiptaAtWork** [comment]
Any projected date for this change to go in and version upgrade of the cordova-plugin-badge?

**Comment by katzer** [comment]
thanks

**Pull request merged**
